void main() {
  throwError();
}

void throwError() => throw Exception('Something went wrong!');
